### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 47.

### ISSUE THREAD

**Issue by jerryhuang01** [economia/svg-mapper#3]
while running with 'example.svg', it returns as the following error code (node v4.2.6; npm v3.8.8; svg-mapper@0.0.4 w/ npm rebuild; many thanks!!!):

$ svg-mapper example.svg -z 6-8 
Generating metadata for example.svg
Creating directories
Starting tile generation. Using 4 cores to do 6 jobs.
Started job #1 of 6 total.
Started job #2 of 6 total.
Started job #3 of 6 total.
Started job #4 of 6 total.
Done job #1. Still processing jobs #2, 3, 4. Jobs remaining: 2.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

Started job #5 of 6 total.
Done job #2. Still processing jobs #3, 4, 5. Jobs remaining: 1.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

Started job #6 of 6 total.
Done job #3. Still processing jobs #4, 5, 6. Jobs remaining: 0.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

Done job #4. Still processing jobs #5, 6. Jobs remaining: 0.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

Done job #6. Still processing jobs #5. Jobs remaining: 0.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

Done job #5.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-mapper/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

All done, tiles are now in same directory as example.svg

**Comment by jerryhuang01** [comment]
fixed by manually updated canvas module
